apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: yce-multus-manager
  name: webhook-service
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    control-plane: yce-multus-manager
  ports:
    - port: 1443
      targetPort: 1443

